### PR TITLE
Bazel initial support: Zexe

### PR DESCRIPTION
**Pull request by mobileink**
Tested on MacOS and Debian 9.

This and Marlin are mutually dependent; neither will build until both are merged.

The Marlin PR is [61](https://github.com/o1-labs/marlin/pull/61)

### CODE REVIEW

**Review by bkase — CHANGES_REQUESTED** [review]
Same as my comment on https://github.com/o1-labs/marlin/pull/61

**Comment by mobileink** [comment]
Fixed oversight: put cargo/ in bzl, to segregate pure bazel stuff and minimize top-level clutter.

**Review by bkase — APPROVED** [review]
@mobileink can follow up with a fix for keeping them in sync in a later PR

**Comment by mobileink** [comment]
Cancelling, will submit a fresh PR based on pinned version.

**Pull request closed without merging**
